### ISSUE TITLE
Lat/long data for other train endpoints

### ISSUE THREAD

**Issue by jwzabrenski** [dmuth/SeptaStats#15]
It could be beneficial to return lat/longs for each station visited in:

/api/current/train/{train no}

/api/current/train/{train no}/history/average

**Comment by dmuth** [comment]
Took care of this in 7595f455.  The 3 train-related endpoints now return lat/lon data.

In detail:

`curl -s https://www.septastats.com/api/current/train/585 |jq .data[0]
{
  "nextstop": "Delaware Valley College",
  "Minutes Late": "1",
  "lat": "40.30580",
  "lon": "-75.13080"
}

$ curl -s https://www.septastats.com/api/current/train/585/history |jq .data[0]
{
  "nextstop": "St. Davids",
  "Minutes Late - Yesterday": "2",
  "Minutes Late - 2 Days Ago": "1",
  "Minutes Late - 5 Days Ago": "11",
  "Minutes Late - 6 Days Ago": "0",
  "Minutes Late - 7 Days Ago": "2",
  "lat": "40.04450",
  "lon": "-75.36040"
}

$ curl -s https://www.septastats.com/api/current/train/585/history/average |jq .data[0]
{
  "nextstop": "St. Davids",
  "Average Minutes Late": "2.285714",
  "lat": "40.04450",
  "lon": "-75.36040"
}
`
