### ISSUE TITLE
CORS requests

### ISSUE THREAD

**Issue by jwzabrenski** [dmuth/SeptaStats#16]
Running into an issue with CORS requests, getting:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.septastats.com/api/current/train/809. (Reason: CORS header 'Access-Control-Allow-Origin' missing)

Any way to allow CORS requests or use JSONP for GET requests?

**Comment by dmuth** [comment]
I've never heard of "CORS" before.  Can you point me to some FAQs/Documentation?  Some code/output examples would also be great.

Thanks,

-- Doug

**Comment by jwzabrenski** [comment]
Sure,

Detailed overview with code examples: [http://www.html5rocks.com/en/tutorials/cors/](http://www.html5rocks.com/en/tutorials/cors/)
How to enable CORS server side: [http://enable-cors.org/server.html](http://enable-cors.org/server.html)
Full documentation: [https://www.w3.org/TR/cors/](https://www.w3.org/TR/cors/)

The code I was trying was this Ajax jQuery request:
`$.ajax({
  url: 'http://www.septastats.com/api/current/system/latest',
  type:"GET",
    dataType:"json",
    crossDomain: true,
    success: function(response) {
console.log("OK");
    },
    error: function(object, xhr, options) {
      console.log(xhr.status + " " + xhr.responseText);
    }
  });`

The xhr status and responseText both returned 'undefined' along with that error message from my initial post.

Please let me know if you need any other information.

Thanks
John

**Comment by dmuth** [comment]
Okay, I got an initial working version of this, as my test results below show.  This should allow you to start working against the API.

I'm not thrilled that I had to put the config into the nginx settings, because these headers are also being sent for static content.  So I'm going to keep this open until I put the changes into the actual PHP code.

```
$ ./test-cors-settings.sh  http://www.septastats.com/
# 
# Testing method 'GET' on URL 'http://www.septastats.com///'
# 
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

# 
# Testing method 'OPTIONS' on URL 'http://www.septastats.com///'
 # 
HTTP/1.1 405 Not Allowed

# 
# Testing method 'GET' on URL 'http://www.septastats.com///api/current/system'
# 
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

# 
# Testing method 'OPTIONS' on URL 'http://www.septastats.com///api/current/system'
# 
HTTP/1.1 204 No Content
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 1728000
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since

# 
# All done!
# 
```

**Comment by jwzabrenski** [comment]
Cool, working fine now.

Thanks!

**Comment by dmuth** [comment]
Okay, I just put in a more permanent fix--the headers are now served up via the HTTP endpoints in the PHP code, and I backed out the changes I made to nginx.

I'll close this one out, but don't hesitate to re-open it if I missed an endpoint or something.
