### ISSUE TITLE
Septa Trains website and API calls failing for Latest Info on Lines

### ISSUE THREAD

**Issue by ghost** [dmuth/SeptaStats#26]
/api/current/line/{train line}/{inbound, outbound}/latest

returning the following errors for each line:

<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <title>Slim Application Error</title>
        <style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style>
    </head>
    <body>
        <h1>Slim Application Error</h1>
        <p>The application could not run because of the following error:</p>
        <h2>Details</h2>
        <div>
            <strong>Type:</strong> Predis\Connection\ConnectionException
        </div>
        <div>
            <strong>Code:</strong> 110
        </div>
        <div>
            <strong>Message:</strong> Connection timed out [tcp://redis:6379]
        </div>
        <div>
            <strong>File:</strong> /htdocs/vendor/predis/predis/src/Connection/AbstractConnection.php
        </div>
        <div>
            <strong>Line:</strong> 168
        </div>
        <h2>Trace</h2>
        <pre>#0 /htdocs/vendor/predis/predis/src/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection-&gt;onConnectionError('Connection time...', 110)
#1 /htdocs/vendor/predis/predis/src/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection-&gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /htdocs/vendor/predis/predis/src/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection-&gt;createResource()
#3 /htdocs/vendor/predis/predis/src/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection-&gt;connect()
#4 /htdocs/vendor/predis/predis/src/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection-&gt;connect()
#5 /htdocs/vendor/predis/predis/src/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection-&gt;getResource()
#6 /htdocs/vendor/predis/predis/src/Connection/StreamConnection.php(290): Predis\Connection\StreamConnection-&gt;write('*2\r\n$3\r\nGET\r\n$3...')
#7 /htdocs/vendor/predis/predis/src/Connection/AbstractConnection.php(123): Predis\Connection\StreamConnection-&gt;writeRequest(Object(Predis\Command\StringGet))
#8 /htdocs/vendor/predis/predis/src/Client.php(326): Predis\Connection\AbstractConnection-&gt;executeCommand(Object(Predis\Command\StringGet))
#9 /htdocs/vendor/predis/predis/src/Client.php(309): Predis\Client-&gt;executeCommand(Object(Predis\Command\StringGet))
#10 /htdocs/lib/query/base.class.php(85): Predis\Client-&gt;__call('get', Array)
#11 /htdocs/lib/query/line.class.php(97): Septa\Query\Base-&gt;redisGet('line/getTrains-...')
#12 /htdocs/lib/endpoints/api.class.php(305): Septa\Query\Line-&gt;getTrainsLatest('Trenton', 'Outbound', 1, 10)
#13 [internal function]: Septa\Endpoints\Api-&gt;Septa\Endpoints\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#14 /htdocs/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#15 /htdocs/vendor/slim/slim/Slim/Route.php(325): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#16 /htdocs/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(114): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /htdocs/vendor/slim/slim/Slim/Route.php(297): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /htdocs/vendor/slim/slim/Slim/App.php(433): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /htdocs/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(114): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /htdocs/vendor/slim/slim/Slim/App.php(315): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /htdocs/index.php(129): Slim\App-&gt;run()
#22 {main}</pre>
    </body>
</html>

**Comment by dmuth** [comment]
Okay it's fixed:

```
$ curl https://www.septastats.com/api/current/line/paoli-thorndale/inbound/latest
{
    "metadata": {
        "elapsed": 0.29406309127807617,
        "_comment": "Latest train info for this line over the last 5 minutes.",
        "line": "Paoli\/Thorndale",
        "direction": "Inbound"
    },
    "data": [
        {
            "id": "516-Doylestown",
            "time": "2018-12-15T12:23:00",
            "late": "3",
            "lat": "40.243447166667",
            "lon": "-75.284834666667",
            "nextstop": "9th St",
            "source": "Malvern",
            "dest": "Doylestown"
        }
    ]
}
```

Root cause was self-inflicted--I historically have used Iptables to do some pretty hardcore filtering on boxes that I manage.  Ran into a bit of a learning curve with Docker because Docker sets up a number of its own chains that do things like rewrite IP addresses and such.  Over the last few weeks I was adding some rules to my Iptables config by hand and testing them out.  In the middle of that, I had to upgrade the size of my Droplet which involved a reboot, at which point the more restrictive iptables rules which were on disk kicked in, and caused the outage you observed.

It is unclear why my alarms that check the API did not fire--I'm guessing what you were seeing did return HTTP 2xx, so that's something I will have to look into separately.

Thanks for reporting this, and one bit of good news is that no data was lost as I was still pulling data from SEPTA's API successfully.

-- Doug
